#!/bin/bash
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi
if [ "$branch" = "stage" ]; then
  echo "You can't commit directly to stage branch"
  exit 1
fi
if [ "$branch" = "dev" ]; then
  echo "You can't commit directly to dev branch"
  exit 1
fi

#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged